#spring.application.name=Idea
## Server
#server.port=8080
#
## MySQL Database
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/banksystem
#
#spring.datasource.username=root
#spring.datasource.password=Anil@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate / JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://dpg-d95ntn0js32c7384fjmg-a.oregon-postgres.render.com:5432/project_emp

spring.datasource.username=project_emp_user
spring.datasource.password=yPbwKAtrsDQpAqFgl09Vbo5krKNG8m3a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true